

# Creating the namespace in the kubernete cluster
- hosts: master
# Defining the remote server where the k8 module will manage the objects
  remote_user: ubuntu   # Using Remote user as ubuntu
  tasks:
 
    - name: copying demo with playbook
      become: true
      ansible.builtin.copy:
        src: demo.yaml
        dest: /home/ubuntu/demo.yaml
        owner: ubuntu
        mode: '0644'


    - name: applying Nginx demo
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f demo.yaml
      args:
        chdir: $HOME
