- hosts: master
  remote_user: ubuntu 
  tasks:
 
    - name: copying demo with playbook
      become: true
      ansible.builtin.copy:
        src: demo.yaml
        dest: /home/ubuntu/demo.yaml
        owner: ubuntu
        mode: '0644'


    - name: applying Nginx demo
      become: yes
      become_user: ubuntu
      shell: kubectl apply -f demo.yaml
      args:
        chdir: $HOME
